### PR TITLE
Added animations for some header elements and for the loading posts element 

### PR DESCRIPTION
**Pull request by rodrigo0345**
Really needed to separate the normal desktop Nav from the mobile Nav in order for the AnimatePresence to work bc it can only detect elements being mounted and unmounted, something that was not happening before.

### CODE REVIEW

**Comment by lloyd-december** [comment]
@rodrigo0345 Is it somehow possible to submit this code without the prettier adjustments? I think you could add "loading" animations when "clicking" on a post, would be easier and cool?

**Comment by rodrigo0345** [comment]
@llo7d sure, I'll give it a try both to the prettier formatting and to the clicking on posts animation.

**Comment by lloyd-december** [comment]
Too many changes, " goes to '  and its hard to tell what is going on. @rodrigo0345

**Comment by rodrigo0345** [comment]
> Too many changes, " goes to '  and its hard to tell what is going on. @rodrigo0345 

Yes, totally agree, it makes everything look messy. I already resolved that issue but I'm still trying to work on the clicking a post's animation.

**Pull request closed without merging**
