### PR TITLE
Highight "How it Works" link when active fixed

### PR DESCRIPTION
**Pull request by Siphiwo**

### CODE REVIEW

**Review by llo7d — APPROVED** [review]
Good fix, thank you!

**Review by llo7d — CHANGES_REQUESTED** [review]
Also add a on hover ;)

**Comment by Siphiwo** [comment]
> Also add a on hover ;)

Will do. Working on allowing user to delete account. This will include the post created by the user as well : )

**Comment by llo7d** [comment]
This is the database schema: /users/"UID"/posts/"POST-TITLE"

**Pull request merged**
