### PR TITLE
Home page made responsive 

### PR DESCRIPTION
**Pull request by tyzrex**
I hope you check this contribution by me I tried to make it responsive and if it works then I hope you merge the change

### CODE REVIEW

**Comment by llo7d** [comment]
This is awesome, great work!

Small issue when clicking on "load more" @tyzrex 
https://gyazo.com/63562640aa95378b96f246486c6a87c0

**Comment by tyzrex** [comment]
I'll try to fix it tomorrow thanks for the info

**Comment by llo7d** [comment]
and if your really into it, you could also make the post page:
https://gyazo.com/a0f58a04200bba5f15d634721b9712bf

Here is the original Figma desgin:
https://youtube.com/watch?v=VgMB7bCbjo4&si=EnSIkaIECMiOmarE&t=519

This is the design I inspired from, sorry, I cannot find the original Figma one.
https://www.figma.com/file/lluo35BvCz8iz0kPLZnaKr/Web-Service---UI-Kit?node-id=0%3A1&t=PGmDyw2ujk8Lqr9S-1

**Comment by tyzrex** [comment]
Okay I'll look into it. I have pushed the load more bug fix check it out if
that works for you

**Comment by llo7d** [comment]
Looks good to me! Great work @tyzrex

**Pull request merged**
