### PR TITLE
Create page and preview post page responsive

### PR DESCRIPTION
**Pull request by tyzrex**

### CODE REVIEW

**Comment by llo7d** [comment]
Great stuff! @tyzrex 
Profile page would be the last one if your into it!

**Comment by llo7d** [comment]
Sorry,
I accidently closed it.

Please also add make the view post page responsive @tyzrex

**Comment by tyzrex** [comment]
Which one is the view page?

**Comment by llo7d** [comment]
@tyzrex Sorry, I ment the My profile and My Posts page

**Comment by tyzrex** [comment]
Do you have the figma files?

**Comment by llo7d** [comment]
Only this one:
https://www.figma.com/file/lluo35BvCz8iz0kPLZnaKr/Web-Service---UI-Kit?node-id=0%3A1&t=S7L0visq21HllHQS-1

Seems like I accidently deleted the original design in Figma.

**Pull request merged**
